using System.Buffers;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Channels;
using AzureBackup.Core.Models;
using AzureBackup.Core.Services;
using Xunit;
using Xunit.Abstractions;

namespace AzureBackup.Tests;

/// <summary>
/// W6 Phase 1 (CDC inner-loop speedup) safety net: pins the EXACT
/// content-defined-chunking output of <see cref="ChunkingService.ChunkAndStreamChangedAsync"/>
/// for a set of deterministic, machine-independent input vectors.
///
/// <para>
/// The existing <see cref="ChunkAndStreamChangedSinglePassTests"/> verify the
/// streaming contract (coverage, ordering, dedup, file hash) but NOT that the
/// chunk BOUNDARIES are bit-identical. Boundaries are the load-bearing CDC
/// invariant: a single shifted boundary re-chunks the entire file, changes
/// every downstream SHA-256 chunk hash, and defeats deduplication against every
/// pre-existing backup. The CDC inner-loop rewrite (deferred per-chunk copy,
/// rolling-hash scan over the scratch span, removal of the redundant
/// per-boundary <c>Array.Clear(window)</c>) must therefore be provably
/// boundary-preserving.
/// </para>
///
/// <para>
/// Strategy: each vector's chunk set is reduced to a compact fingerprint
/// (SHA-256 over every chunk's index/offset/length/hash) and the whole set of
/// fingerprints is compared against a pinned golden report captured from the
/// known-good pre-rewrite implementation. ANY boundary, length, or content
/// drift moves a fingerprint and fails <see cref="ChunkBoundaries_MatchGoldenReport"/>.
/// </para>
///
/// <para>
/// Content is generated by an explicit xorshift64 PRNG (NOT
/// <see cref="System.Random"/>, whose sequence is not contractually stable
/// across runtimes) and a constant-byte fill, so the vectors reproduce
/// byte-for-byte on any machine, OS, or .NET build.
/// </para>
/// </summary>
public class ChunkBoundaryGoldenVectorTests : IDisposable
{
    private readonly string _testDir;
    private readonly ChunkingService _chunkingService = new();
    private readonly ITestOutputHelper _output;

    // The golden report captured from the known-good pre-rewrite CDC
    // implementation. One line per vector:
    //   {name}|chunks={n}|bytes={total}|file={first16OfFileHash}|fp={fingerprint}
    // If a future change to the CDC algorithm is INTENTIONAL, re-capture this
    // value (the test failure prints the new actual report) and update it in
    // the SAME commit that changes the algorithm, with a note explaining why
    // boundaries moved. Do NOT update it casually -- a changed fingerprint
    // means every existing backup loses dedup against the new chunking.
    private const string ExpectedGoldenReport =
        "bin-random-4mb|chunks=11|bytes=4194304|file=B54BC3658D1C67FA|fp=488EEA5718D78F3BF5A39BD05CB20BE6A405939E6D6B400FD75783A588F5C3D2\n" +
        "txt-random-2mb|chunks=28|bytes=2097152|file=60A0CE8D3F668031|fp=D4954A49D5BAFADAA1F177A41B6EB8669934F5116E40FA5F5ABC78EC386402F4\n" +
        "mp4-random-8mb|chunks=3|bytes=8388608|file=3B1C07BBE6D4311C|fp=2FE60FB45CAFCFD78E7BDFFB747F5343B0BBE3EAD42ED185F64A4E4EA073391D\n" +
        "const-maxcap-bin-4mb|chunks=4|bytes=4194304|file=304723FE1A4265D5|fp=E4648BBCE50FC16B3A4AF82A2F9AA5EAA7A36C08D5832704D263C1185313C011\n" +
        "tiny-bin-1kb|chunks=1|bytes=1024|file=13A0DF28698DC2C9|fp=334FD20E06328DA484A932DE0D1E29A9C0956FB64863A0C34BC081489D809BC1\n";

    public ChunkBoundaryGoldenVectorTests(ITestOutputHelper output)
    {
        _output = output;
        _testDir = Path.Combine(Path.GetTempPath(), "azbk-golden-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(_testDir);
    }

    public void Dispose()
    {
        try { Directory.Delete(_testDir, recursive: true); } catch { /* best effort */ }
    }

    /// <summary>
    /// Pins the exact chunk boundaries across every vector. This is the
    /// regression gate for the CDC inner-loop rewrite.
    /// </summary>
    [Fact]
    public async Task ChunkBoundaries_MatchGoldenReport()
    {
        var report = new StringBuilder();
        foreach (var vector in Vectors)
        {
            var path = await WriteVectorAsync(vector);
            var (chunks, fileHash) = await ChunkAsync(path);
            var total = chunks.Sum(c => (long)c.Length);
            report.Append(vector.Name)
                  .Append("|chunks=").Append(chunks.Count)
                  .Append("|bytes=").Append(total)
                  .Append("|file=").Append(fileHash[..16])
                  .Append("|fp=").Append(Fingerprint(chunks))
                  .Append('\n');
        }

        var actual = report.ToString();
        _output.WriteLine("==== ACTUAL GOLDEN REPORT (copy into ExpectedGoldenReport on intentional change) ====");
        _output.WriteLine(actual);

        Assert.Equal(ExpectedGoldenReport, actual);
    }

    /// <summary>
    /// Independently validates that every DISPATCHED payload's bytes hash to
    /// the chunk hash recorded in metadata. This is the direct correctness
    /// check for the deferred per-chunk bulk copy: if the rewrite ever copies
    /// the wrong bytes (wrong run length, wrong source offset, off-by-one at a
    /// scratch-refill boundary), the payload's SHA-256 will not match the
    /// metadata hash and this test fails -- independently of the pinned report.
    /// </summary>
    [Fact]
    public async Task DispatchedPayloadBytes_MatchChunkHash()
    {
        foreach (var vector in Vectors)
        {
            var path = await WriteVectorAsync(vector);
            var channel = Channel.CreateUnbounded<ChunkPayload>();
            var (chunks, _) = await _chunkingService.ChunkAndStreamChangedAsync(
                path, existingHashes: [], channel.Writer, cdcProgress: null);
            channel.Writer.Complete();

            var dispatched = await DrainAsync(channel.Reader);
            try
            {
                // No dedup pre-seeding, so every produced chunk is dispatched.
                Assert.Equal(chunks.Count, dispatched.Count);
                foreach (var payload in dispatched)
                {
                    var actualHash = Convert.ToHexString(
                        SHA256.HashData(payload.Data.AsSpan(0, payload.Length)));
                    Assert.Equal(payload.Info.Hash, actualHash);
                    Assert.Equal(payload.Info.Length, payload.Length);
                }
            }
            finally
            {
                ReturnAll(dispatched);
            }
        }
    }

    /// <summary>
    /// Pins the chunk-length distribution per vector so the report fingerprint
    /// is interpretable and so we can assert which CDC branches each vector
    /// exercises (mask-hit boundaries vs max-chunk-size capping). The
    /// constant-byte vector is expected to force max-size capping because a
    /// constant input drives the rolling hash to a fixed point that does not
    /// satisfy the boundary mask, so no content boundary ever fires.
    /// </summary>
    [Fact]
    public async Task ConstantByteVector_ForcesMaxChunkSizeCapping()
    {
        var vector = Vectors.Single(v => v.Name == "const-maxcap-bin-4mb");
        var path = await WriteVectorAsync(vector);
        var (chunks, _) = await ChunkAsync(path);

        // Every chunk except the trailing remainder must be exactly the
        // default-config max chunk size (1 MB) because no content boundary
        // fires on constant input.
        const int defaultMaxChunk = 1 * 1024 * 1024;
        Assert.True(chunks.Count >= 2, $"expected multiple capped chunks, got {chunks.Count}");
        for (var i = 0; i < chunks.Count - 1; i++)
        {
            Assert.Equal(defaultMaxChunk, chunks[i].Length);
        }
    }

    private async Task<(List<ChunkInfo> Chunks, string FileHash)> ChunkAsync(string path)
    {
        var channel = Channel.CreateUnbounded<ChunkPayload>();
        var result = await _chunkingService.ChunkAndStreamChangedAsync(
            path, existingHashes: [], channel.Writer, cdcProgress: null);
        channel.Writer.Complete();
        ReturnAll(await DrainAsync(channel.Reader));
        return result;
    }

    /// <summary>
    /// Boundary-sensitive fingerprint over every chunk's identity. Captures
    /// index, offset, length, and content hash so any re-chunking is visible.
    /// </summary>
    private static string Fingerprint(List<ChunkInfo> chunks)
    {
        var sb = new StringBuilder();
        foreach (var c in chunks)
        {
            sb.Append(c.Index).Append(':')
              .Append(c.Offset).Append(':')
              .Append(c.Length).Append(':')
              .Append(c.Hash).Append('\n');
        }
        return Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(sb.ToString())));
    }

    private async Task<string> WriteVectorAsync(Vector vector)
    {
        var path = Path.Combine(_testDir, vector.Name + vector.Extension);
        var bytes = vector.ConstantByte is { } constByte
            ? ConstantBytes(constByte, vector.SizeBytes)
            : XorShiftBytes(vector.Seed, vector.SizeBytes);
        await File.WriteAllBytesAsync(path, bytes);
        return path;
    }

    /// <summary>
    /// Deterministic, runtime-independent pseudo-random bytes via xorshift64.
    /// </summary>
    private static byte[] XorShiftBytes(ulong seed, int length)
    {
        var buf = new byte[length];
        var x = seed == 0 ? 0x9E3779B97F4A7C15UL : seed;
        for (var i = 0; i < length; i++)
        {
            x ^= x << 13;
            x ^= x >> 7;
            x ^= x << 17;
            buf[i] = (byte)(x >> 24);
        }
        return buf;
    }

    private static byte[] ConstantBytes(byte value, int length)
    {
        var buf = new byte[length];
        Array.Fill(buf, value);
        return buf;
    }

    private sealed record Vector(
        string Name,
        string Extension,
        int SizeBytes,
        ulong Seed,
        byte? ConstantByte = null);

    // Vectors deliberately span multiple ChunkSizeConfig profiles and CDC
    // branches:
    //  - default config (.bin): 64 KB-1 MB, mask 18 (~256 KB avg)
    //  - small config (.txt):   16 KB-128 KB, mask 16 (~64 KB avg)
    //  - media config (.mp4):   1 MB-64 MB, mask 22 (~4 MB avg)
    //  - constant-byte:         forces max-chunk-size capping (no mask hit)
    //  - tiny:                  below min-chunk-size -> single-chunk fast path
    private static readonly Vector[] Vectors =
    [
        new("bin-random-4mb", ".bin", 4 * 1024 * 1024, Seed: 0xA1A1A1A1A1A1A1A1),
        new("txt-random-2mb", ".txt", 2 * 1024 * 1024, Seed: 0xB2B2B2B2B2B2B2B2),
        new("mp4-random-8mb", ".mp4", 8 * 1024 * 1024, Seed: 0xC3C3C3C3C3C3C3C3),
        new("const-maxcap-bin-4mb", ".bin", 4 * 1024 * 1024, Seed: 0, ConstantByte: 0xAB),
        new("tiny-bin-1kb", ".bin", 1024, Seed: 0xD4D4D4D4D4D4D4D4),
    ];

    private static async Task<List<ChunkPayload>> DrainAsync(ChannelReader<ChunkPayload> reader)
    {
        var payloads = new List<ChunkPayload>();
        await foreach (var p in reader.ReadAllAsync())
        {
            payloads.Add(p);
        }
        return payloads;
    }

    private static void ReturnAll(List<ChunkPayload> payloads)
    {
        foreach (var p in payloads)
        {
            ArrayPool<byte>.Shared.Return(p.Data);
        }
    }
}
